<?php
/**
 * Created by PhpStorm.
 * User: stefan
 * Date: 31.07.16
 * Time: 15:40
 */

namespace Request\Classes\Rewrite;

use Model\Classes\AbstractModel;
use Request\Classes\Request\Param\Exception;
use Request\Model\Request\Attribute;
use Request\Model\Request\Param;

class Attributes extends AbstractModel
{
	public static function factory($params)
	{
		$instance = new static();
		if (is_array($params))
		{
			foreach ($params as $param_key => $param_value)
			{
				$instance->offsetSet($param_key, $param_value);
			}
		}

		return $instance;
	}

	public function add($value)
	{
		if ( ! $value instanceof Attribute)
		{
			throw new Exception('Param needs to be instance of Param, got '.gettype($value));
		}
		return parent::add($value); // TODO: Change the autogenerated stub
	}
}